/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.31
 * Generated at: 2018-11-15 01:31:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.resources.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_005fpopup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"popup_layer\" id=\"popup_terms\" style=\"display: none;\">\r\n");
      out.write("\t<div class=\"popup_layer_bg\"></div>\r\n");
      out.write("\t<div class=\"popup_layer_cont\" style=\"margin-top: -231.5px; margin-left: -315px;\">\r\n");
      out.write("\t\t<div class=\"popup_head\">\r\n");
      out.write("\t\t\t<span>KH정보교육원 이용약관</span>\r\n");
      out.write("\t\t\t<a href=\"javascript:fnLayerClose();\">&nbsp;</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"popup_cont\">\r\n");
      out.write("\t\t\t<p class=\"popup_ment\">KH정보교육원의 이용약관은 다음과 같습니다.</p>\r\n");
      out.write("\t\t\t<div class=\"clause_content\"><b>KH정보교육원 회원 약관</b><br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<b>제 1 장 총칙</b><br>\r\n");
      out.write("<br>\r\n");
      out.write("제 1 조 목적<br>\r\n");
      out.write("<br>\r\n");
      out.write("이 약관은 KH정보교육원이 제공하는 서비스인 http://www.iei.or.kr의 이용조건 및 절차에 관한 사항과 기타 필요한 사항을 규정함을 목적으로 합니다.<br>\r\n");
      out.write("<br>\r\n");
      out.write("제 2 조 약관의 효력과 변경<br>\r\n");
      out.write("<br>\r\n");
      out.write("1) 약관은 이용자에게 공시함으로써 효력을 발생합니다.<br>\r\n");
      out.write("<br>\r\n");
      out.write("2) KH정보교육원은 교육원 사정상 변경의 경우와 영업상 중요사유가 있을 때 약관을 변경할 수 있으며, 변경된 약관은 전항과 같은 방법으로 효력을 발생합니다.<br>\r\n");
      out.write("<br>\r\n");
      out.write("제 3 조 약관 외 준칙<br>\r\n");
      out.write("<br>\r\n");
      out.write("이 약관에 명시되지 않은 사항이 관계법령에 규정되어 있을 경우에는 그 규정에 따릅니다.<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<b>제 2 장 회원 가입과 서비스 이용</b><br>\r\n");
      out.write("<br>\r\n");
      out.write("제 1 조 이용 계약의 성립<br>\r\n");
      out.write("<br>\r\n");
      out.write("1)KH정보교육원에서 운영하는 모든 회원서비스는 이 약관에 동의한 이용자들에게 무료로 제공 되는 서비스입니다.<br>\r\n");
      out.write("이용자가 \"동의합니다\" 버튼을 누르면 이 약관에 동의하는 것으로 간주됩니다.<br>\r\n");
      out.write("<br>\r\n");
      out.write("2) 회원에 가입하여 서비스를 이용하고자 하는 희망자는 회사에서 요청하는 개인 신상정보를 제공해야 합니다.<br>\r\n");
      out.write("<br>\r\n");
      out.write("3) 등록정보<br>\r\n");
      out.write("KH정보교육원은 이용자 등록정보를 집단적인 형태로 사용할 수는 있지만 각 이용자 개인 정보는, 불법적이거나 기타 다른 불온한 문제를 일으킬 경우를 제외하고, 이용자의 동의 없이는 절대 공개하지 않습니다.<br>\r\n");
      out.write("KH정보교육원을 이용하여 타인에게 피해를 주거나 미풍양속을 해치는 행위를(즉 욕설, 비방성글, 인신공격성 발언, 사회적질서를 혼란시키는 유언비어등)한 이용자는 회원자격이 박탈되며, 이로 인해 발생되는 모든 사회적문제는 KH정보교육원에서 책임지지 않습니다.<br>\r\n");
      out.write("<br>\r\n");
      out.write("4) 약관의 수정<br>\r\n");
      out.write("KH정보교육원은 이 약관을 변경할 수 있으며 변경된 약관은 서비스 화면에 게재하거나 기타 다른 방법으로 이용자에게 공지함으로써 효력을 발생합니다.<br>\r\n");
      out.write("<br>\r\n");
      out.write("5) ID와 패스워드<br>\r\n");
      out.write("이용자번호(ID)와 비밀번호(password)에 관한 모든 관리책임은 이용자에게 있습니다. <br>\r\n");
      out.write("이용자에게 부여된 이용자번호(ID) 및 비밀번호(password)의 관리소홀, 부정사용에 의하여 발생하는 모든 결과에 대한 책임은 이용자에게 있습니다. <br>\r\n");
      out.write("자신의 ID가 부정하게 사용된 경우 이용자는 반드시 KH정보교육원에 그 사실을 통보해야 합니다.<br>\r\n");
      out.write("<br>\r\n");
      out.write("6) 사용자 정보<br>\r\n");
      out.write("KH정보교육원에 기재하는 모든 이용자 정보는 이름을 포함하여 모두 실제 데이타인 것으로 간주됩니다.<br>\r\n");
      out.write("실명이나 실제 정보를 입력하지 않은 사용자는 법적인 보호를 받을 수 없으며, KH정보교육원의 서비스 제한 조치를 받을 수 있습니다.<br>\r\n");
      out.write("<br>\r\n");
      out.write("7) 광고 게재 및 컨텐츠 제휴<br>\r\n");
      out.write("KH정보교육원은 광고수익과 컨텐츠 제휴를 기반으로 컨텐츠 서비스를 제공하고 있습니다.<br>\r\n");
      out.write("KH정보교육원의 서비스를 이용하고자 하는 이용자는 광고게재및 컨텐츠제휴에 대해 동의하는 것으로 간주됩니다.<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<b>제 3 장 계약 해지 및 서비스 이용제한</b> <br>\r\n");
      out.write("<br>\r\n");
      out.write("제 1 조 계약 해지 및 이용제한<br>\r\n");
      out.write("<br>\r\n");
      out.write("이용자가 이용 계약을 해지 하고자 하는 때에는 이용자 본인이 직접 온라인을 통해 관리자에게 메일을 보내어 해지 신청을 하여야 합니다.<br>\r\n");
      out.write("<br>\r\n");
      out.write("회사는 이용자가 다음 사항에 해당하는 행위를 하였을 경우 사전 통지 없이 이용 계약을 해지 하거나 또는 기간을 정하여 서비스 이용을 중지할 수 있습니다.<br>\r\n");
      out.write("<br>\r\n");
      out.write("(1) 공공 질서 및 미풍 양속에 반하는 경우<br>\r\n");
      out.write("<br>\r\n");
      out.write("(2) 범죄적 행위에 관련되는 경우<br>\r\n");
      out.write("<br>\r\n");
      out.write("(3) 이용자가 국익 또는 사회적 공익을 저해할 목적으로 서비스 이용을 계획 또는 실행 할 경우<br>\r\n");
      out.write("<br>\r\n");
      out.write("(4) 타인의 서비스 아이디 및 비밀 번호를 도용한 경우<br>\r\n");
      out.write("<br>\r\n");
      out.write("(5) 타인의 명예를 손상시키거나 불이익을 주는 경우<br>\r\n");
      out.write("<br>\r\n");
      out.write("(6) 같은 사용자가 다른 아이디로 이중 등록을 한 경우<br>\r\n");
      out.write("<br>\r\n");
      out.write("(7) 서비스에 위해를 가하는 등 서비스의 건전한 이용을 저해하는 경우<br>\r\n");
      out.write("<br>\r\n");
      out.write("(8) 기타 관련법령이나 회사가 정한 이용조건에 위배되는 경우<br>\r\n");
      out.write("<br>\r\n");
      out.write("제 2 조 이용 제한의 해제 절차<br>\r\n");
      out.write("<br>\r\n");
      out.write("(1) 회사는 규정에 의하여 이용제한을 하고자 하는 경우에는 그 사유, 일시 및 기간을 정하여 서면 또는 전화 등의 방법에 의하여 해당 이용자 또는 대리인에게 통지합니다. 다만, 회사가 긴급하게 이용을 정지할 필요가 있다고 인정하는 경우에는 그러하지 아니합니다.<br> \r\n");
      out.write("<br>\r\n");
      out.write("(2) 제1항의 규정에 의하여 이용정지의 통지를 받은 이용자 또는 그 대리인은 그 이용정지의 통지에 대하여 이의가 있을 때에는 이의신청을 할 수 있습니다. <br>\r\n");
      out.write("<br>\r\n");
      out.write("(3) 회사는 제2항의 규정에 의한 이의신청에 대하여 그 확인을 위한 기간까지 이용정지를 일시 연기할 수 있으며, 그 결과를 이용자 또는 그 대리인에게 통지합니다. <br>\r\n");
      out.write("<br>\r\n");
      out.write("(4) 회사는 이용정지 기간 중에 그 이용정지 사유가 해소된 것이 확인된 경우 에는 이용정지조치를 즉시 해제합니다.<br>\r\n");
      out.write("<br>\r\n");
      out.write("제 3 조 이용자의 게시물<br>\r\n");
      out.write("<br>\r\n");
      out.write("회사는 이용자가 게시하거나 등록하는 서비스 내의 내용물이 다음 각 사항에 해당된다고 판단되는 경우에 사전 통지 없이 삭제할 수 있습니다.<br>\r\n");
      out.write("<br>\r\n");
      out.write("(1) 다른 이용자 또는 제 3자를 비방하거나 중상 모략으로 명예를 손상시키는 내용인 경우<br>\r\n");
      out.write("<br>\r\n");
      out.write("(2) 공공질서 및 미풍 양속에 위반되는 내용인 경우<br>\r\n");
      out.write("<br>\r\n");
      out.write("(3) 범죄적 행위에 결부된다고 인정되는 내용일 경우<br>\r\n");
      out.write("<br>\r\n");
      out.write("(4) 제 3자의 저작권 등 기타 권리를 침해하는 내용인 경우<br>\r\n");
      out.write("<br>\r\n");
      out.write("(5) 기타 관계 법령이나 회사에서 정한 규정에 위배되는 경우<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<b>제 4 장 계약변경 등</b><br>\r\n");
      out.write("<br>\r\n");
      out.write("제 1 조 계약사항의 변경<br>\r\n");
      out.write("<br>\r\n");
      out.write("(1) 이용자는 주소 또는 이용계약 내용을 변경하거나, 서비스 를 해지할 경우에는 전화나 서비스를 통해서 이용계약을 변경/ 해지하여야 합니다.<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<b>제 5 장 정보의 제공</b><br>\r\n");
      out.write("<br>\r\n");
      out.write("제 1 조 정보의 제공<br>\r\n");
      out.write("<br>\r\n");
      out.write("(1) 회사는 이용자가 서비스 이용 중 필요가 있다고 인정되는 다양한 정보에 대해서는 전자우편이나 서신우편 등의 방법으로 이용자에게 제공할 수 있습니다.<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<b>제 6 장 손해 배상</b>\r\n");
      out.write("<br>\r\n");
      out.write("제 1 조<br>\r\n");
      out.write("<br>\r\n");
      out.write("1) 손해배상 <br>\r\n");
      out.write("KH정보교육원은 서비스 이용과 관련하여 이용자에게 발생한 어떠한 손해에 관하여도 책임을 지지 않습니다. <br>\r\n");
      out.write("서비스 이용으로 발생한 분쟁에 대해 소송이 제기될 경우 KH정보교육원의 소재지를 관할하는 법원을 관할법원으로 합니다. <br>\r\n");
      out.write("<br>\r\n");
      out.write("[부 칙] <br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("( 시 행 일 ) 이 약관은 2015년 01월 12일부터 시행합니다.<br>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
