/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.31
 * Generated at: 2018-11-25 14:10:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class joinPageAgree_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"/resources/png/03_KH정보교육원_원형컬러.png\">\r\n");
      out.write("<title>회원가입</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color: #D5D5D5;\">\r\n");
      out.write("<script src=\"//ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"//maxcdn.bootstrapcdn.com/bootstrap/latest/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link href=\"//maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css\" rel=\"stylesheet\" id=\"bootstrap-css\">\r\n");
      out.write("<script src=\"//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"//code.jquery.com/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\t.material-switch > input[type=\"checkbox\"] {\r\n");
      out.write("    display: none;   \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".material-switch > label {\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    height: 0px;\r\n");
      out.write("    position: relative; \r\n");
      out.write("    width: 40px;  \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".material-switch > label::before {\r\n");
      out.write("    background: rgb(0, 0, 0);\r\n");
      out.write("    box-shadow: inset 0px 0px 10px rgba(0, 0, 0, 0.5);\r\n");
      out.write("    border-radius: 8px;\r\n");
      out.write("    content: '';\r\n");
      out.write("    height: 16px;\r\n");
      out.write("    margin-top: -8px;\r\n");
      out.write("    position:absolute;\r\n");
      out.write("    opacity: 0.3;\r\n");
      out.write("    transition: all 0.4s ease-in-out;\r\n");
      out.write("    width: 40px;\r\n");
      out.write("}\r\n");
      out.write(".material-switch > label::after {\r\n");
      out.write("    background: rgb(255, 255, 255);\r\n");
      out.write("    border-radius: 16px;\r\n");
      out.write("    box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.3);\r\n");
      out.write("    content: '';\r\n");
      out.write("    height: 24px;\r\n");
      out.write("    left: -4px;\r\n");
      out.write("    margin-top: -8px;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: -4px;\r\n");
      out.write("    transition: all 0.3s ease-in-out;\r\n");
      out.write("    width: 24px;\r\n");
      out.write("}\r\n");
      out.write(".material-switch > input[type=\"checkbox\"]:checked + label::before {\r\n");
      out.write("    background: inherit;\r\n");
      out.write("    opacity: 0.5;\r\n");
      out.write("}\r\n");
      out.write(".material-switch > input[type=\"checkbox\"]:checked + label::after {\r\n");
      out.write("    background: inherit;\r\n");
      out.write("    left: 20px;\r\n");
      out.write("}\r\n");
      out.write("    \r\n");
      out.write("    #login-form > div {\r\n");
      out.write("        margin: 15px 0;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #container{\r\n");
      out.write("    \tmargin-top : 20px;\r\n");
      out.write("    \tmargin-left : 300px;\r\n");
      out.write("    \twidth : 1000px;\r\n");
      out.write("    \theight : 900px;\r\n");
      out.write("    \t\r\n");
      out.write("    }\r\n");
      out.write("    #contents-2{\r\n");
      out.write("  \r\n");
      out.write("    \tpadding-left: 250px;\r\n");
      out.write("    \tpadding-right: 150px;\r\n");
      out.write("    \ttext-align: left; width : 100%;\r\n");
      out.write("    \theight : 10%;\r\n");
      out.write("    \t\r\n");
      out.write("    }\r\n");
      out.write("    #contents-3{\r\n");
      out.write("    \tpadding-left: 250px;\r\n");
      out.write("    \tpadding-right: 150px;\r\n");
      out.write("    \ttext-align: left; width : 100%;\r\n");
      out.write("    \theight : 75%;\r\n");
      out.write("    }\r\n");
      out.write("    #contents-3 div{\r\n");
      out.write("    \tborder : 1px solid gray;\r\n");
      out.write("    }\r\n");
      out.write("    #contents-3 p{\r\n");
      out.write("    \tfont-weight: bolder;\r\n");
      out.write("    }\r\n");
      out.write("\t#kh-agree{\r\n");
      out.write("\t\twidth : 100%;\r\n");
      out.write("\t\theight : 25%;\r\n");
      out.write("\t\toverflow: auto;\r\n");
      out.write("\t}\r\n");
      out.write("\t#privacy{\r\n");
      out.write("\t\twidth : 100%;\r\n");
      out.write("\t\theight : 25%;\r\n");
      out.write("\t\toverflow: auto;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t#join{\r\n");
      out.write("\t\tbackground-color : #003399;\r\n");
      out.write("\t\tdisplay: block;\r\n");
      out.write("\t\twidth : 200px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("              \r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t$('#allCheckSwitch').change(function(){\r\n");
      out.write("\t\tif($('#allCheckSwitch').is(\":checked\")){\r\n");
      out.write("\t\t\t$('#khAgreeCheckSwitch').prop('checked',true);\r\n");
      out.write("\t\t\t$('#privacyAgreeCheckSwitch').prop('checked',true);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\t$('#khAgreeCheckSwitch').prop('checked',false);\r\n");
      out.write("\t\t\t$('#privacyAgreeCheckSwitch').prop('checked',false);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("\tfunction check(){\r\n");
      out.write("\t\tvar khAgree = $('input:checkbox[id=khAgreeCheckSwitch]').is(\":checked\");\r\n");
      out.write("\t\tvar privacyAgree = $('input:checkbox[id=privacyAgreeCheckSwitch]').is(\":checked\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(khAgree==true && privacyAgree==true)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tlocation.href=\"/member/joinPage.kh\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"모든 이용약관에 동의 하셔야 합니다.\")\t;\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("                  \r\n");
      out.write("                        \r\n");
      out.write("<div id=\"container\"  align=\"center\">\r\n");
      out.write("    <div id=\"contents-1\">\r\n");
      out.write("            \t<a href=\"/index.jsp\"><img height=80px width=300px src=\"/resources/png/01_KH정보교육원_가로컬러.png\"/></a><br>\r\n");
      out.write("    </div>\r\n");
      out.write("\t<br><br>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"contents-2\" >\r\n");
      out.write("        \r\n");
      out.write("            <span style=\"font-size:20px;\"><b>KH정보교육원</b>을 찾아주셔서 감사합니다.</span><br>\r\n");
      out.write("\t\t\t<span>회사는 <b><u>회원가입, 상담, 서비스 신청 등을 위해 아래와 같은 개인정보를 수집</u></b>하고 있습니다.</span><br>\r\n");
      out.write("\t\t\t<span>회원가입을 원하실 경우 내용 확인 후 <b><u>동의</u></b>해 주시기 바랍니다.</span><br>\r\n");
      out.write("\t\t\t<hr style=\"border:2px solid black;\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"contents-3\" >    \r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("           \t<span class=\"material-switch pull-left\">\r\n");
      out.write("                <input id=\"allCheckSwitch\"  type=\"checkbox\"/>\r\n");
      out.write("                <label for=\"allCheckSwitch\"  class=\"label-primary\"></label>\r\n");
      out.write("                <span> 전체 이용 약관 동의 </span>\r\n");
      out.write("                <br><br>\r\n");
      out.write("            </span>\r\n");
      out.write("           \t<br><br>\r\n");
      out.write("           \t<span class=\"material-switch pull-left\">\r\n");
      out.write("                <input id=\"khAgreeCheckSwitch\" type=\"checkbox\"/>\r\n");
      out.write("                <label for=\"khAgreeCheckSwitch\" class=\"label-primary\"></label>\r\n");
      out.write("                <span> kh정보교육원 이용약관 동의 </span><span style=\"color:blue;\">(필수)</span>\r\n");
      out.write("            </span>\r\n");
      out.write("          <br><br>\r\n");
      out.write("           \t<div id=\"kh-agree\">\r\n");
      out.write("           \t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/resources/common/kh_agree.jsp", out, false);
      out.write("\r\n");
      out.write("           \t</div>\r\n");
      out.write("           <br><br>\r\n");
      out.write("           \t<span class=\"material-switch pull-left\">\r\n");
      out.write("                <input id=\"privacyAgreeCheckSwitch\"  type=\"checkbox\"/>\r\n");
      out.write("                <label for=\"privacyAgreeCheckSwitch\" class=\"label-primary\"></label>\r\n");
      out.write("                <span> 개인정보 보호정책 및 개인정보 수집에 대한 이용 안내 동의</span><span style=\"color:blue;\">(필수)</span>\r\n");
      out.write("            </span>\r\n");
      out.write("            <br><br>\r\n");
      out.write("           \t<div id=\"privacy\">\r\n");
      out.write("           \t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/resources/common/privacy.jsp", out, false);
      out.write("\r\n");
      out.write("           \t</div>\r\n");
      out.write("           \t<br>\r\n");
      out.write("           \t<center><button id=\"join\" type=\"button\" class=\"btn btn-primary\" onclick=\"return check();\">회원가입</button></center>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"footer_bar\">\r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/resources/common/main_footer_bar.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<div id=\"footer\">\r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/resources/common/main_footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
