/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.31
 * Generated at: 2018-11-19 12:03:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class loginPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<script src=\"//ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"//maxcdn.bootstrapcdn.com/bootstrap/latest/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link href=\"//maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("\t\r\n");
      out.write("    body {\r\n");
      out.write("        background: #f8f8f8;\r\n");
      out.write("        padding: 60px 0;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #login-form > div {\r\n");
      out.write("        margin: 15px 0;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .container{\r\n");
      out.write("    \theight : 300px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    input{\r\n");
      out.write("    \theight : 200px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #member-join{\r\n");
      out.write("    \theight : 30px;\r\n");
      out.write("    \twidth : 100%;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #id-pw-find{\r\n");
      out.write("     height :30px;\r\n");
      out.write("    \twidth : 100%;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    input:focus{\r\n");
      out.write("    \tborder: 3px solid blue;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    button:active{\r\n");
      out.write("    \theight:98%;\r\n");
      out.write("    \twidth:98%;\r\n");
      out.write("    }\r\n");
      out.write("    #member-join a:active{\r\n");
      out.write("   \t \twidth:140px;\r\n");
      out.write("    }\r\n");
      out.write("    #id-pw-find a:active{\r\n");
      out.write("   \t \twidth:140px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #member-join a{\r\n");
      out.write("    \tbackground : #283444;\r\n");
      out.write("    \tfont-size : 13px;\r\n");
      out.write("    \tcolor : #fff;\r\n");
      out.write("    \tfloat:right;\r\n");
      out.write("    \tdisplay:block;\r\n");
      out.write("    \theight:100%;\r\n");
      out.write("    \tline-height: 30px;\r\n");
      out.write("    \twidth : 150px;\r\n");
      out.write("    \ttext-align: center;\r\n");
      out.write("    \ttext-decoration: none;\r\n");
      out.write("    \t\r\n");
      out.write("    }\r\n");
      out.write("    #id-pw-find a{\r\n");
      out.write("    \tbackground : #283444;\r\n");
      out.write("    \tfont-size : 13px;\r\n");
      out.write("    \tcolor : #fff;\r\n");
      out.write("    \tfloat:right;\r\n");
      out.write("    \tdisplay:block;\r\n");
      out.write("    \theight:100%;\r\n");
      out.write("    \tline-height: 30px;\r\n");
      out.write("    \twidth : 150px;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\ttext-decoration: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\"  align=\"center\">\r\n");
      out.write("    <div class=\"col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2\">\r\n");
      out.write("            \t<a href=\"/index.jsp\"><img height=120px src=\"/resources/jpg/kh_info.jpg\"/></a>    \r\n");
      out.write("            <div class=\"panel-body\">\r\n");
      out.write("                <form action=\"/member/login.kh\" method=\"post\" id=\"login-form\">\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <input type=\"text\"  class=\"form-control\" name=\"userId\" placeholder=\"아이디\" autofocus>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <input type=\"password\"  class=\"form-control\" name=\"userPw\" placeholder=\"비밀번호\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <button type=\"submit\" style=\"background : #993800;\" class=\"form-control btn btn-primary\">로그인</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("                <br>\r\n");
      out.write("               \t<p align=\"left\" id=\"member-join\">\r\n");
      out.write("                <span align=\"left\">KH 정보교육원의 회원이 아니신가요?</span> \r\n");
      out.write("                <a href=\"\">KH회원가입 하기</a>\r\n");
      out.write("                </p>\r\n");
      out.write("                <p align=\"left\" id=\"id-pw-find\">\r\n");
      out.write("                <span align=\"left\">아이디나 비밀번호를 잊어버리셨나요?</span> \r\n");
      out.write("                <a href=\"\">아이디/비밀번호 찾기</a>\r\n");
      out.write("                </p>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"footer_bar\">\r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/resources/common/main_footer_bar.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<div id=\"footer\">\r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/resources/common/main_footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
